[package]
name = "discrakt"
version = "0.1.0"
edition = "2021"
authors = ["afonsojramos"]
description = "Easy to Use Trakt/Plex Discord Rich Presence"
repository = "https://github.com/afonsojramos/discrakt"
license = "MIT"
keywords = ["discord", "trakt", "rust"]

[dependencies]
discord-rich-presence = "0.1"
ureq = { version = "2.4" }
configparser = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
