[package]
name = "discrakt"
version = "2.2.3"
edition = "2021"
authors = ["afonsojramos"]
description = "Easy to Use Trakt/Plex Discord Rich Presence"
repository = "https://github.com/afonsojramos/discrakt"
license = "MIT"
keywords = ["discord", "trakt", "rust"]
readme = "README.md"
exclude = [
    ".github/*",
    "images/*.psd",
    "credentials.ini",
    ".gitignore",
]

[dependencies]
discord-rich-presence = "0.2.0"
ureq = { version = "2.4.0", features = ["json"] }
configparser = { version = "3.0.2", features = ["indexmap"] }
serde = { version = "1.0.163", features = ["derive"] }
chrono = "0.4.34"
webbrowser = "0.8.7"

[profile.release]
strip = "debuginfo"
