name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.57", "1.58"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build Binary
        run: cargo build

      - name: Run Unit Tests
        run: cargo test

  publish-linux:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/discrakt && mv target/release/discrakt target/release/discrakt_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/discrakt_amd64
            credentials.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-win:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/discrakt.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create silent executable
        uses: DamianReeves/write-file-action@v1
        with:
          path: src/main.rs
          contents: |
            #![windows_subsystem = "windows"]
          write-mode: prepend

      - name: Build silent executable
        run: cargo build --all --release && mv target/release/discrakt.exe target/release/discrakt_silent.exe

      - name: Release silent executable
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/discrakt_silent.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-mac:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/discrakt && mv target/release/discrakt target/release/discrakt_darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/discrakt_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
